import { formatMacroBriefingContentForTelegram } from "@/macro/macroBriefingContent.js";
import {
	boldUnderline,
	italic,
} from "@/notifications/telegram/escapeMarkdownV2.js";
import { formatUserDateTime } from "@/notifications/telegram/formatUserDateTime.js";
import type { TelegramUserSettings } from "@/storage/telegramUserSettings.js";

export type MacroBriefingMessageInput = {
	content: string;
	generatedAt: Date;
};

export function formatMacroBriefingMessage(
	briefing: MacroBriefingMessageInput,
	userDateTimeSettings?: Pick<TelegramUserSettings, "locale" | "timezone">,
): string {
	const generatedAt = formatUserDateTime(briefing.generatedAt, {
		locale: null,
		timezone: null,
		...userDateTimeSettings,
		formatOptions: {
			dateStyle: "long",
		},
	});

	return [
		boldUnderline(`WhalePilot Macro Briefing for ${generatedAt}`),
		"",
		formatMacroBriefingContentForTelegram(briefing.content),
		"",
		italic(
			"This information was generated by the WhalePilot Macro Briefing System for use by the decision-making AI to evaluate assets in the current macro environment. This is not financial advice.",
		),
	].join("\n");
}

export const NO_MACRO_BRIEFING_MESSAGE = "No macro briefing available yet\\.";

export const NO_MACRO_FOR_DECISION_MESSAGE =
	"No macro briefing was available for this decision\\.";
